name: ci_experiments
channels: 
  - defaults
  - conda-forge
  - intel
  - anaconda
  - anaconda-fusion
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - pip = 23.*
  - scikit-learn
  - torchvision
  - pip:
    - ylearn
    - networkx==2.8.8
    - cdt